### ISSUE TITLE
Programs are huge when drag'n'droping

### ISSUE THREAD

**Issue by marekdedic** [janzarsky/scout-planner#235]
The program appears to be much bigger when in the middle of a drag'ndrop

![image](https://github.com/janzarsky/scout-planner/assets/3134692/d783ddf7-3ea6-4faf-b863-03adac1c238d)

**Comment by janzarsky** [comment]
I could not reproduce it. @marekdedic please send browser info

**Comment by marekdedic** [comment]
:/ Now I can't replicate it either... I'll be on the lookout

I'm on FF 110.0.1 on Debian

**Comment by janzarsky** [comment]
could not reproduce this
