### ISSUE TITLE
Strange highlights in tray when drag'n'droping 

### ISSUE THREAD

**Issue by marekdedic** [janzarsky/scout-planner#238]
When drag'n'droping an existing program anywhere into the tray, the green "+" area gets highlighted (blue overlay). When the moved program is held over another program already in the tray, that program gets highlighted as well. This is a bit strange and misleading as in the rest of the app, the highlight is under the cursor.

**Comment by janzarsky** [comment]
So now you should be able to only drop programs at the first field in the tray (the add button). Dropping on another program should swap those two programs (but this is not reliable yet).

**Comment by marekdedic** [comment]
Nope, swapping doesn't work for me - either it does nothing or it adds the program to the tray (even when dropping on another program already in tray)
