### ISSUE TITLE
Drag'n'drop uses the original cursor location as the reference point

### ISSUE THREAD

**Issue by marekdedic** [janzarsky/scout-planner#249]
When  drag'n'dropping a larger program, the "reference point", i.e. the place which sets where the program should be placed, is the original cursor position at the start of the drag (relative to the program being dragged). This is slightly confusing

For example, if you take a large program, start dragging from a point somewhere on the right side of the program and release the program in the same place where you picked it up (the same cursor location), the program actually shifts to the right.

I propose to use the top-left corner of the program as the reference point (or maybe a point a little bit inside of the corner to account for low user precision?) - that would fix the aforementioned issue.

Related to #245

**Comment by janzarsky** [comment]
I am not going to solve this one. The move icon is in the top left corner for exactly this reason. If it ever comes to implementing #245, than it should definitely be part of it.

**Comment by marekdedic** [comment]
Then I would suggest to only make the top left corner draggable, this is just counterintuitive.
