### ISSUE TITLE
Different drag'n'drop look (outline, transparency) in Chromium vs. FF

### ISSUE THREAD

**Issue by marekdedic** [janzarsky/scout-planner#250]
I get a white outline and full opacity in Chromium and transparency and no outline in FF

Chromium:
![image](https://github.com/janzarsky/scout-planner/assets/3134692/5cb01b9b-5451-403f-8b25-ac089ad70358)

FF:
![image](https://github.com/janzarsky/scout-planner/assets/3134692/887adff6-fee8-4850-bcb8-93aae3f85cfa)

(There's #235 going on in FF as well)

- both on Debian testing
- Chromium Version 113.0.5672.63 (Official Build) built on Debian 12.0, running on Debian 12.0 (64-bit)
- FF 110.0.1 (64bit)

**Comment by janzarsky** [comment]
I am going to leave this as it is, there is no significant user impact
