### ISSUE TITLE
Timetable width settings doesn't seem to do anything?

### ISSUE THREAD

**Issue by marekdedic** [janzarsky/scout-planner#292]
Hi,
thanks for the option to set timetable width. However, it seems to me that it doesn't do anything? At least for https://harmonogram.zarsky.name/ULS2022 setting it to "Nejužší" and "Širší" produces the same timetable I think...

**Comment by janzarsky** [comment]
It sets the minimum width of an hour. So on bigger screen, the result is the same because the hour is wider than the minimum. I can set it differently of course, but I need example where the existing presets are not working well.
