### ISSUE TITLE
FR: Emoji should stay horizontal even in vertical text layout

### ISSUE THREAD

**Issue by marekdedic** [janzarsky/scout-planner#294]
The ability for the text to be vertical is great, however, it looks weird with emoji:

![image](https://github.com/janzarsky/scout-planner/assets/3134692/bb185afc-a34a-4ee6-8be3-b3ba138849dc)

It would be more readable if the emoji were actually horizontal (but still the whole text would stay vertical, so in 1 column, just with each emoji rotated back to its original orientation)

**Comment by marekdedic** [comment]
And actually, maybe they should be the other way around? Like, from top to bottom? But that probably opens a whole another can of worms and corner cases...

**Comment by janzarsky** [comment]
I rather not do this. When there are other fields present, you have to rotate your head anyways...
![image](https://github.com/janzarsky/scout-planner/assets/748663/74cac092-3ce2-4577-b7bd-e9afe6a5554d)
The timetable would need to be smart about whether it is just emojis or not.
