### ISSUE TITLE
How to do different divisions for different programme blocks?

### ISSUE THREAD

**Issue by marekdedic** [janzarsky/scout-planner#53]
We have some programme blocks where the participants are divided in halves and some other blocks where the same participants would be divided into thirds. Currently I only see one way to do this - set up 6 groups and do programs for 2 or 3 at once - which is quite cumbersome...

Is there a better way to do this?

**Comment by janzarsky** [comment]
On data level, I would not change it, I would still have groups that "attend" programs. What we can do is create some kind of hierarchy, so that Participants 1, Participants 2, etc. would be grouped under just "Participants". Then in the program edit modal we can have buttons like for programs with participants split into 2/3/4 groups.

**Comment by marekdedic** [comment]
I'm not sure that won't come back to bite you 😀 For example of you split one group into halves and later thirds, you'd need to change the number of subgroups from 2 to 6 (or, generally, the least common multiple) and redo all the programs that were previously split...

Maybe it would be simpler to do it on the program level?

**Comment by janzarsky** [comment]
I will try to describe how it could work (mostly as a note to myself):
- on data level, there would be a flag for a program, something like "part of a program block"
- these "block" programs would not overlap, they would rather stack vertically
- block programs starting at the same time would not trigger a rule violation
- for example, if you have 4 programs for a group A starting at the same time, they would show as if group A would be split in 4
- visually, it would look like the space that would be occupied by 1 program was split vertically in 4, but not by any grid. Two block programs next to each other would have different vertical divisions

How would it work (at least at the beginning):
- before rendering, the algorithm would look for groups of overlapping "block" programs, the groups would be transitively closed (don't judge me, I am not sure if it is the proper term), for example there may be two block programs overlapping on Tue 9:00 and then another three overlapping at Fri 11:00
- then, generally, the algorithm would try to render each group, if it fails, all programs in a group will be just rendered as regular programs (and thus triggering the overlap rule)
- all programs in a group must be for the same participant groups
- then a block wrapper will be created - beginning and end calculated as minimum/maximum over all programs
- inside the wrapper, all programs will be rendered, stacked vertically

Potential simplification for the first version:
- only programs of same beginning and end (thus also duration) can be used.

To solve:
- how will the drag and drop look like

Benefits:
- no need to define number of programs for a given block - useful for situations where participants can choose what to attend
- no data relation between programs, no new entities (blocks, subgroups)
- backward compatible

**Comment by marekdedic** [comment]
This looks good to me, however, I'm still wondering if the tradeoff of data simplicity to algorithms complexity is worth it - the proposed solution modifies the data format minimally, however, it makes the layout algorithm fairly complex.

An alternative that makes the opposite trade-off would be to modify the data format so that you can have nested programs - with that approach you'd have a very minimal program that as a property has a list of "sub-programs" that are rendered without overlap and rule violations - basically as you described.

Also, would the proposed solution be able to handle cases like this where not all programs start at the same time? I think that's what you meant by transitive closure, I'm not sure though...

![image](https://user-images.githubusercontent.com/3134692/212044582-84b15763-3242-4d91-92f1-834f2e15effb.png)

**Comment by janzarsky** [comment]
This would not be supported. In the proposed solution, there would be 6 rows - for each program.

**Comment by janzarsky** [comment]
Let's start with use cases:

1. VM use case - known number of participants, two groups that are different and that do not change (CLK/VLK) - this is supported
![image](https://user-images.githubusercontent.com/748663/216607819-9993897a-12f7-46d2-abc8-a4c650e2d341.png)
2. ULS use case - unknown number of participants, potentially large number, each can choose where to go for each block, arbitrary number of programs at the same time - this would be covered by the proposed solution. Currently you have to create groups manually which does not make sense.
![image](https://user-images.githubusercontent.com/748663/216608222-fb6b4b10-27de-4b6e-8a8e-0a6106e024a8.png)
3. Odyssea use case - known number of participants, arbitrary division per block, multiple programs in a row - not supported. Currently you have to create groups that allow arbitrary division (usually 6 or 12).
![image](https://user-images.githubusercontent.com/748663/216608641-0563c974-4584-4bf2-a369-a66a85c5c9a1.png)

**Comment by janzarsky** [comment]
All three use cases should be available now.

The data model is the following: each program now has an integer (zero by default) which specifies the order within a block. The blocks however, are just implicit, there is no new entity.

Check this example: https://harmonogram.zarsky.name/block-demo

What is not yet done:
* blocks for programs without groups #113
* drag&drop for blocks #112

**Comment by marekdedic** [comment]
Thanks!
the demo looks promising :)

I tried to play with it a little and the block are not visually separated for me: https://harmonogram.zarsky.name/odyssea

Drag&drop can do a lot for the UX and ease of use, looking forward to that :)

**Comment by janzarsky** [comment]
> I tried to play with it a little and the block are not visually separated for me: https://harmonogram.zarsky.name/odyssea
would you like it to be separated? Some kind of extra border? Do I understand it correctly? Do you want the block be visible as an entity from the user perspective?

**Comment by marekdedic** [comment]
Ok, I just opened it again by clicking the link and now they are seprated - previously, there was no white space between the two :/

**Comment by janzarsky** [comment]
so.. I should start bumping versions to have caches invalidated properly :D

**Comment by marekdedic** [comment]
I added 2 more and this is what I see:

![image](https://user-images.githubusercontent.com/3134692/220894367-b3c58d92-0532-4c65-aa7e-796786a846ab.png)

To repro:
1. Add Program C
2. Add Program D an hour later, with block=1
3. Move Program D to the same time as C
4. Realize I forgot to assign groups, add them to both C and D
5. See that they're overlapping
