### ISSUE TITLE
Feature request: Easier creating/moving programmes in empty days

### ISSUE THREAD

**Issue by marekdedic** [janzarsky/scout-planner#55]
When I want to create a programme in a day that is currently empty, this is quite cumbersome as I have to create the programme in another day and then move it by manually changing the date.

Possible solutions: Show adjacent days even if they're empty. Maybe they could be shown only when drag&dropping a programme?

**Comment by janzarsky** [comment]
I added some kind of workaround that partially solves this - always at least 3 days are shown. Also when there is a gap of at most 3 days, the days will be shown even if there is no program.
