### ISSUE TITLE
Better font handling for large timetables

### ISSUE THREAD

**Issue by marekdedic** [janzarsky/scout-planner#88]
We have a [fairly large timetable](https://harmonogram.zarsky.name/ULS2022). When trying to print this, that's a problem. Some of the text is wrapped (line-broken) too much to the point it's unreadable. Some text is too small. If I set the time step to 5 min, the whole page becomes too wide (#73).

**Comment by janzarsky** [comment]
check this https://harmonogram.zarsky.name/ULS2022-fix, the width is not yet fixed, but short programs should look better

**Comment by marekdedic** [comment]
Looks great, thanks!
